
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://donggram-db.c0ux4rjo51ph.ap-northeast-2.rds.amazonaws.com:3306/donggramDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: donggram

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
server:
  port: 8084

cloud:
  aws:
    s3:
      bucket: image-profile-bucket
      stack.auto: false
    region.static: ap-northeast-2

    credentials:
      accessKey: AKIA5QUFMHM2225UJANN
      secretKey: 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
