spring:
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:donggram
        driver-class-name: org.h2.Driver
        username: sa
        password:

#    datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/donggram
#        username: admin
#        password: menten7272!


    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: create
        defer-datasource-initialization: true