spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://donggram-db.c0ux4rjo51ph.ap-northeast-2.rds.amazonaws.com:3306/donggramDB?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
        username: admin
        password: donggram

    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        open-in-view: false
        show-sql: true
        hibernate.hbm2ddl.auto: create
        generate-ddl: true
