
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://donggram-db.c0ux4rjo51ph.ap-northeast-2.rds.amazonaws.com:3306/donggramDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: donggram

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
server:
  port: 8085